#!/bin/bash

usage()
{
cat << EOF
usage: $0 options

OPTIONS:
-r run# (NEEDED!)
-e expname (def: current experiment, example: xppe7815)
#-d directory for output files (default: ftc diretory of specified experiment)
EOF
}

RUN=-1
EXP='xxx'
QUEUE=psanaq
DIRNAME='xxx'

while getopts "e:r:h" OPTION
do
    case $OPTION in
	h)
	    usage
	    exit 1
	    ;;
	r) 
	    RUN=$OPTARG
	    ;;
	e)
	    EXP=$OPTARG
	    ;;
	?)
	    usage
	    exit
	    ;;
	esac
done

if [ $RUN -le 0 ]; then
    echo 'we need a run as input, use -r option'
    exit
fi

RUN=`echo $RUN |  sed 's/^0*//'`
RUN=`printf "%0*d\n" 4 $RUN`
HUTCH=${EXP:0:3}

#EXE='/reg/g/psdm/sw/releases/ana-current/arch/x86_64-rhel7-gcc48-opt/bin/smldata'
EXE='/reg/g/psdm/sw/conda/inst/miniconda2-prod-rhel7/envs/ana-1.3.59/bin/smldata'
RUNS=`ls /reg/d/psdm/$HUTCH/$EXP/xtc/*r$RUN*`
#. /reg/g/psdm/etc/ana_env.sh
#. /reg/g/psdm/bin/sit_setup.sh

if [ ! -d  ./smallDataLogs ]; then
    echo 'now we will make ./smallDataLogs/'
    mkdir ./smallDataLogs 
fi

for NRUN in $RUNS;
do
    FTC=`echo $NRUN | sed s:\/xtc:\/scratch:g | sed s/.xtc/.smd.xtc/g`
    LOGDIR='/reg/d/psdm/'$HUTCH'/'$EXP'/scratch/smallDataLogs'
    LOG=$LOGDIR'/log_run'$RUN'_%J.log'
    if [ ! -d  $LOGDIR ]; then
	echo 'now we will make ' $LOGDIR
	mkdir $LOGDIR
    fi

    CMD=`echo bsub -q $QUEUE -o $LOG $EXE -f $NRUN -o $FTC`
    echo $CMD
    $CMD
done


