#!/bin/bash

export PATH=$PATH:/reg/g/xpp/scripts:/reg/neh/operator/xppopr/bin
CURREXP=`get_curr_exp`
HUTCH=`get_hutch_name`
cd /reg/d/psdm/$HUTCH/$CURREXP/results/smalldata_tools
#LASTRUN=4
LASTRUN=`get_lastRun`
while true; do
	CREATE_TIME=`date '+%m/%d/%Y_%H:%M:%S'`
	EXP_RUN=`get_lastRun`
	if [ $EXP_RUN -ge $LASTRUN ]; then
            HASH5=`ls -t /reg/d/psdm/$HUTCH/$CURREXP/hdf5/smalldata/$CURREXP*Run*$LASTRUN*h5 | wc | awk {'print $1'}`
	    echo 'Last Run: '$EXP_RUN ', checked at ' $CREATE_TIME ', checking to process run ' $LASTRUN

	    if [ $HASH5 -eq 1 ]; then
		echo 'send job for run ' $LASTRUN 
		./examples/avimageRun -a -r $LASTRUN
		let "LASTRUN+=1" 
		sleep 30
	    fi
	fi
	sleep 10
done
