#!/bin/bash

export PATH=$PATH:/reg/g/xpp/scripts:/reg/neh/operator/xppopr/bin
THISEXP=`get_curr_exp`
HUTCH=${THISEXP:0:3}
cd /reg/d/psdm/$HUTCH/$THISEXP/results/smalldata_tools
LASTRUN=`get_lastRun`
while true; do
	CREATE_TIME=`date '+%m/%d/%Y_%H:%M:%S'`
	CURREXP=`get_curr_exp`
	EXP_RUN=`get_lastRun`
	if [[ $EXP_RUN -ge $LASTRUN ]] && [[ $CURREXP == $THISEXP ]]; then
            #HASH5=`ls -t /reg/d/psdm/$HUTCH/$THISEXP/hdf5/smalldata/$THISEXP*Run*$LASTRUN*h5 | wc | awk {'print $1'}`
	    #now require minimum time since file has been written to!
            HASH5=`find /reg/d/psdm/$HUTCH/$THISEXP/hdf5/smalldata/$THISEXP*Run*$LASTRUN*h5 -type f -mmin +2 | wc -l`
	    echo 'Last Run: '$EXP_RUN ', checked at ' $CREATE_TIME ', checking to process run ' $LASTRUN

	    if [ $HASH5 -eq 1 ]; then
		echo 'send job for run ' $LASTRUN 
		#./examples/avimageRun -a -r $LASTRUN
		./examples/cubeRun -r $LASTRUN
		let "LASTRUN+=1" 
		sleep 30
	    fi
	fi
	sleep 10
done
