#!/bin/bash
source /reg/d/iocCommon/All/xpp_env.sh
#export PROCSERV="/reg/g/pcds/package/epics/3.14/extensions/R3.14.12/bin/$EPICS_HOST_ARCH/procServ --allow --ignore ^D^C --logstamp --noautorestart"
export TIME=`date +%s`
export NAME="monitor-lsmallData.$HOSTNAME.$TIME"

CURREXP=`/reg/g/xpp/scripts/get_curr_exp`
if [[ $CURREXP =~ 'xpp' ]]; then
    cd /reg/d/psdm/xpp/$CURREXP/results/smalldata_tools/examples/scripts
else
    cd /reg/d/psdm/xcs/$CURREXP/results/smalldata_tools/examples/scripts
fi
$PROCSERV --logfile /tmp/$NAME --name monitor-smallData 40001 ./monitor-smallData-production
