#!/bin/bash

usage()
{
cat << EOF
usage: $0 options

OPTIONS:
-r run# (NEEDED!)
-e expname (def: current experiment, example: xppe7815)
-d directory for output files (default: ftc diretory of specified experiment)
-q queue name (default: psanaq if exp specified, psneh(hi)prioq for current exp)
-n number of events (for testing)
-s run locally
-f no recorder data (faster data access)
EOF
}

export PATH=$PATH:/reg/g/xpp/scripts:/reg/neh/operator/xppopr/bin

RUN=-1
#16 works ok for default smalleData
#also when using MPI, use only one node.....
#for bigger ROI on short run, 32 jobs is better, 64 did not have gain
#
#EXP='xcsx22015'
EXP='xxx'
QUEUE=psanaq
DIRNAME='xxx'
NUMBER_OF_EVENTS=0
SINGLEJOB=0
DAYSHIFT=1
QUEUEREQ='xxx'
XTCAV=0
LIVE=0
LIVEFAST=0
AUTO=0
NORECORDER=0
OFFICIAL=0

while getopts "e:d:r:n:q:hxsfo" OPTION
do
    case $OPTION in
	h)
	    usage
	    exit 1
	    ;;
	r) 
	    RUN=$OPTARG
	    ;;
	e)
	    EXP=$OPTARG
	    ;;
	n)
	    NUMBER_OF_EVENTS=$OPTARG
	    ;;
	q)
	    QUEUEREQ=$OPTARG
	    ;;
	d)
	    DIRNAME=$OPTARG
	    ;;
	f)
	    NORECORDER=1
	    ;;
	o)
	    OFFICIAL=1
	    ;;
	?)
	    usage
	    exit
	    ;;
	esac
done

if [ $RUN -le 0 ]; then
    echo 'we need a run as input, use -r option'
    exit
fi

RUN=`echo $RUN |  sed 's/^0*//'`
RUN=`printf "%0*d\n" 4 $RUN`


ARGSTR=''
if [ $XTCAV -gt 0 ]; then
    ARGSTR=$ARGSTR' --xtcav'
fi
if [ $NORECORDER -gt 0 ]; then
    ARGSTR=$ARGSTR' --norecorder'
fi
if [ $NUMBER_OF_EVENTS -ne 0 ]; then
    ARGSTR=$ARGSTR' --nev '$NUMBER_OF_EVENTS
fi
if [ $EXP != 'xxx' ]; then
    ARGSTR=$ARGSTR' --exp '$EXP
else
    CURREXP=`get_curr_exp`
    EXP=$CURREXP
fi
HUTCH=${EXP:0:3}

BASEDIR=/reg/d/psdm/$HUTCH/$EXP/results
if [ ! -d  $BASEDIR ]; then
    BASEDIR=/reg/d/psdm/$HUTCH/$EXP/res
fi
LOGDIR=$BASEDIR/logs
if [ $DIRNAME != 'xxx' ]; then
    ARGSTR=$ARGSTR' --dir '$DIRNAME
    LOGDIR=$DIRNAME/logs
    if [ ! -d  $DIRNAME ]; then
	echo 'now we will make ' $DIRNAME
	mkdir $DIRNAME
    fi
fi

if [ ! -d  $LOGDIR ]; then
    echo 'now we will make '$LOGDIR
    mkdir $LOGDIR
fi

LDAP='./'
source /reg/g/pcds/setup/pathmunge.sh
pythonpathmunge $LDAP

if [ $OFFICIAL -eq 0 ]; then
    source /reg/g/psdm/etc/psconda.sh
    #conda activate ana-1.3.80
    CMD=`echo python ./examples/MakeLocalPedestal.py \
	$ARGSTR \
        --run $RUN`
    echo $CMD    
    #$CMD
else
    source /reg/g/psdm/etc/psconda.sh
    source conda_setup --reldir /reg/neh/home/cpo/ana-1.3.80
    CMD=`echo epix10ka_pedestals_calibration -d epix10ka2m -e $EXP -r $RUN`
    echo $CMD
    $CMD
    CMD=`echo epix10ka_deploy_constants -D -d epix10ka2m -e $EXP -r $RUN`
    echo $CMD
    $CMD
fi
